spring:
  application:
    name: DataTransferer

  datasource:
    url: ${DATATRANSFERER_DB_URL:jdbc:mariadb://localhost:3306/fresh_potatoes}
    username: ${DATATRANSFERER_DB_USERNAME:root}
    password: ${DATATRANSFERER_DB_PASSWORD:}

  mongodb:
    host: ${DATATRANSFERER_MONGO_HOST:notkulonme.hu}
    username: ${DATATRANSFERER_MONGO_USERNAME:admin}
    password: ${DATATRANSFERER_MONGO_PASSWORD:NagyonTitkosJelszo}
    database: ${DATATRANSFERER_MONGO_DATABASE:dump}
    authentication-database: ${DATATRANSFERER_MONGO_AUTH_DATABASE:admin}

transfer:
  run-on-startup: ${DATATRANSFERER_RUN_ON_STARTUP:true}
  movie-batch-size: ${DATATRANSFERER_MOVIE_BATCH_SIZE:1000}
